name: heals1.0
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.7.6
  - altair
  - cudatoolkit=10.0.*
  - matplotlib=3.1.1
  - nb_conda=2.2.1
  - numpy=1.16.*
  - pandas=0.25.*
  - pytorch=1.2.*
  - scipy=1.3.1
  - tensorboard=1.14.0
  - torchvision=0.4.*
  - tensorflow-gpu
  - pyyaml
  - scikit-learn==0.21.*
  - ipdb
  - seaborn
  - ibm_db
  - xgboost
  - fancyimpute
  - innvestigate
  - shap
  - uwsgi==2.0.18  
  - pip:
    - future==0.17.1
    - ray==0.7.6
    - pytorch-lightning
    - mlflow>=1.2.0
    - boto3
    - git+https://github.com/IBM/AIX360.git#egg=AIX360
    - Flask==1.1.1
