name: metaexplainer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip3
  - python==3.7.6
  - altair
  - matplotlib=3.1.1
  - aix360
  - shap
  - nb_conda=2.2.1
  - numpy>=1.17.*
  - pandas=0.25.*
  - pytorch=1.2.*
  - scipy=1.3.1
  - tensorboard=1.14.0
  - torchvision=0.4.*
  - pyyaml
  - scikit-learn==0.21.*
  - ipdb
  - xgboost=1.0.2
  - seaborn
  - tabulate
  - ibm_db
  - shap
  - uwsgi==2.0.18  
  - pip:
    - future==0.17.1
    - six
    - ontospy==1.9.9.4
    - ray==0.7.6
    - owlready2
    - langchain
    - weaviate-client
    - ragas
    - llama-index 
    - llama-index-experimental
    - langchain
    - langchain_experimental
    - langchain_openai
    - pubmed_lookup
    - eutils
    - nltk
    - xport
    - cvxpy
    - dice-ml
    - transformers
    - sklearn
    - torch
    - openpyxl
    - xlrd==1.2.0
    - bs4
    - requests
    - nltk
    - ipywidgets
    - pytorch-lightning
    - mlflow>=1.2.0
    - boto3
    - git+https://github.com/IBM/AIX360.git#egg=AIX360
    - Flask==1.1.1
