name: heals1.0
channels:
  - pytorch
  - defaults
dependencies:
  - altair
  - cudatoolkit=10.0.130
  - matplotlib=3.1.1
  - nb_conda=2.2.1
  - numpy
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.6
  - pytorch=1.4.0
  - pyyaml=5.3.1
  - scikit-learn=0.23.1
  - scipy
  - seaborn=0.10.1
  - tensorboard=2.1.0
  - toolz=0.10.0
  - torchvision=0.5.0
  - tqdm
  - pip:
    - ipdb
    - flask==1.1.2
    - future==0.17.1
    - mlflow==1.10.0
    - progressbar==2.5
    - pytorch-lightning==0.8.5
    - ray[tune]==0.7.6
    - shap
    - tabulate==0.8.7
    - typing-extensions==3.7.4.1
